import type {
  Project,
  ActivityItem,
  Organization,
  User,
  GeneratedBudget,
  ProcessingStep,
} from "@/types"

export const mockUser: User = {
  id: "usr_01",
  name: "Andrés Mendoza",
  email: "amendoza@constructoraabc.pe",
  role: "Gerente de Presupuestos",
}

export const mockOrg: Organization = {
  id: "org_01",
  name: "Constructora ABC",
  plan: "professional",
  country: "PE",
  currency: "PEN",
}

export const mockProjects: Project[] = [
  {
    id: "proj_01",
    code: "PROJ-2026-001",
    name: "Edificio Los Álamos",
    type: "EDIFICACION",
    status: "APPROVED",
    location: "Miraflores, Lima",
    totalBudget: 840000,
    currency: "PEN",
    progress: 68,
    partidas: 47,
    createdAt: new Date("2026-04-15"),
    updatedAt: new Date("2026-06-05"),
  },
  {
    id: "proj_02",
    code: "PROJ-2026-002",
    name: "Vía San Martín km 12",
    type: "VIAL",
    status: "IN_PROGRESS",
    location: "Piura, Perú",
    totalBudget: 1200000,
    currency: "PEN",
    progress: 34,
    partidas: 63,
    createdAt: new Date("2026-05-02"),
    updatedAt: new Date("2026-06-04"),
  },
  {
    id: "proj_03",
    code: "PROJ-2026-003",
    name: "PTAR Lurín",
    type: "HIDRAULICA",
    status: "DRAFT",
    location: "Lurín, Lima",
    totalBudget: 360000,
    currency: "PEN",
    progress: 12,
    partidas: 28,
    createdAt: new Date("2026-05-20"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "proj_04",
    code: "PROJ-2026-004",
    name: "Subestación Chimbote",
    type: "ELECTRICO",
    status: "DRAFT",
    location: "Chimbote, Áncash",
    currency: "PEN",
    progress: 0,
    partidas: 0,
    createdAt: new Date("2026-06-06"),
    updatedAt: new Date("2026-06-06"),
  },
  {
    id: "proj_05",
    code: "PROJ-2026-005",
    name: "Carretera Cusco–Quillabamba",
    type: "VIAL",
    status: "APPROVED",
    location: "Cusco, Perú",
    totalBudget: 4200000,
    currency: "PEN",
    progress: 91,
    partidas: 89,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-06-07"),
  },
]

export const mockActivity: ActivityItem[] = [
  {
    id: "act_01",
    type: "budget_approved",
    title: "Presupuesto aprobado",
    description: "Versión 3 aprobada y lista para licitación",
    projectName: "Edificio Los Álamos",
    user: "María García",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "act_02",
    type: "export_completed",
    title: "Exportación completada",
    description: "Presupuesto exportado a Excel · 7 hojas",
    projectName: "Vía San Martín km 12",
    user: "Andrés Mendoza",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    badge: "Excel descargado",
  },
  {
    id: "act_03",
    type: "comment_added",
    title: "Comentario en partida",
    description: "\"Revisar rendimiento de excavación en zona rocosa\"",
    projectName: "PTAR Lurín",
    user: "Luis Romero",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: "act_04",
    type: "apu_generated",
    title: "APUs generados por IA",
    description: "28 partidas generadas · confianza promedio 91%",
    projectName: "PTAR Lurín",
    user: "InfraPilot AI",
    timestamp: new Date(Date.now() - 28 * 60 * 60 * 1000),
    badge: "✦ IA",
  },
  {
    id: "act_05",
    type: "tender_submitted",
    title: "Propuesta enviada",
    description: "Licitación Presa San Juan — SENAMHI · S/ 7,850,000",
    projectName: "Presa San Juan",
    user: "Andrés Mendoza",
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000),
  },
]

export const mockAiCredits = { used: 847, total: 1000 }

export const mockTenderCount = 3

export const processingSteps: ProcessingStep[] = [
  {
    id: "step_1",
    label: "Tipo de obra identificado",
    detail: "Edificación — Oficinas corporativas · Categoría: Primera",
    status: "pending",
  },
  {
    id: "step_2",
    label: "Ubicación reconocida",
    detail: "Miraflores, Lima · Zona sísmica 4 · Precios CAPECO Jun-2026",
    status: "pending",
  },
  {
    id: "step_3",
    label: "Especificaciones técnicas extraídas",
    detail: "Concreto f'c=280 · Vidrio spider · 3 ascensores · 2 sótanos",
    status: "pending",
  },
  {
    id: "step_4",
    label: "Estructurando capítulos del presupuesto",
    detail: "7 secciones identificadas",
    status: "pending",
  },
  {
    id: "step_5",
    label: "Calculando metrados y cantidades",
    detail: "6,400 m² construidos · 10 pisos totales",
    status: "pending",
  },
  {
    id: "step_6",
    label: "Asignando precios del catálogo CAPECO",
    detail: "Precios vigentes junio 2026 · Lima",
    status: "pending",
  },
  {
    id: "step_7",
    label: "Generando APUs detallados",
    detail: "58 partidas · materiales, MO y equipos",
    status: "pending",
  },
  {
    id: "step_8",
    label: "Verificando coherencia del presupuesto",
    detail: "Validación cruzada completa",
    status: "pending",
  },
]

export const mockGeneratedBudget: GeneratedBudget = {
  projectName: "Edificio Torre Azul",
  location: "Miraflores, Lima, Perú",
  currency: "PEN",
  confidence: 91,
  sections: [
    {
      id: "sec_01",
      code: "01",
      name: "Obras Preliminares",
      subtotal: 48200,
      items: [
        { id: "i_0101", code: "01.01", name: "Limpieza de terreno", unit: "m2", quantity: 800, unitPrice: 3.8, totalPrice: 3040, isAiGenerated: true, confidence: 0.95 },
        { id: "i_0102", code: "01.02", name: "Trazo y replanteo", unit: "m2", quantity: 800, unitPrice: 4.2, totalPrice: 3360, isAiGenerated: true, confidence: 0.93 },
        { id: "i_0103", code: "01.03", name: "Movilización de maquinaria", unit: "glb", quantity: 1, unitPrice: 12000, totalPrice: 12000, isAiGenerated: true, confidence: 0.88 },
        { id: "i_0104", code: "01.04", name: "Instalaciones provisionales", unit: "glb", quantity: 1, unitPrice: 18400, totalPrice: 18400, isAiGenerated: false },
        { id: "i_0105", code: "01.05", name: "Cerco provisional metálico", unit: "ml", quantity: 120, unitPrice: 95, totalPrice: 11400, isAiGenerated: true, confidence: 0.9 },
      ],
    },
    {
      id: "sec_02",
      code: "02",
      name: "Movimiento de Tierras",
      subtotal: 312000,
      items: [
        { id: "i_0201", code: "02.01", name: "Excavación masiva c/equipo", unit: "m3", quantity: 4800, unitPrice: 28.4, totalPrice: 136320, isAiGenerated: true, confidence: 0.92 },
        { id: "i_0202", code: "02.02", name: "Corte y nivelación de terreno", unit: "m2", quantity: 800, unitPrice: 12.6, totalPrice: 10080, isAiGenerated: true, confidence: 0.9 },
        { id: "i_0203", code: "02.03", name: "Relleno y compactación", unit: "m3", quantity: 1200, unitPrice: 38.5, totalPrice: 46200, isAiGenerated: true, confidence: 0.89 },
        { id: "i_0204", code: "02.04", name: "Eliminación de material excedente", unit: "m3", quantity: 3600, unitPrice: 33.2, totalPrice: 119520, isAiGenerated: true, confidence: 0.94 },
      ],
    },
    {
      id: "sec_03",
      code: "03",
      name: "Concreto Armado — Sótanos",
      subtotal: 1240000,
      items: [
        { id: "i_0301", code: "03.01", name: "Concreto cimientos f'c=210 kg/cm²", unit: "m3", quantity: 480, unitPrice: 346.2, totalPrice: 166176, isAiGenerated: true, confidence: 0.93 },
        { id: "i_0302", code: "03.02", name: "Acero corrugado fy=4200 cimientos", unit: "kg", quantity: 42000, unitPrice: 3.45, totalPrice: 144900, isAiGenerated: true, confidence: 0.91 },
        { id: "i_0303", code: "03.03", name: "Muros pantalla e=25cm", unit: "m2", quantity: 1200, unitPrice: 285.4, totalPrice: 342480, isAiGenerated: true, confidence: 0.87 },
        { id: "i_0304", code: "03.04", name: "Losa de sótano f'c=280 kg/cm²", unit: "m3", quantity: 960, unitPrice: 416.28, totalPrice: 399629, isAiGenerated: true, confidence: 0.9 },
        { id: "i_0305", code: "03.05", name: "Impermeabilización de sótanos", unit: "m2", quantity: 1600, unitPrice: 116.76, totalPrice: 186816, isAiGenerated: true, confidence: 0.85 },
      ],
    },
    {
      id: "sec_04",
      code: "04",
      name: "Estructura Principal",
      subtotal: 2180000,
      items: [
        { id: "i_0401", code: "04.01", name: "Columnas de concreto f'c=280 kg/cm²", unit: "m3", quantity: 864, unitPrice: 454.0, totalPrice: 392256, isAiGenerated: true, confidence: 0.92 },
        { id: "i_0402", code: "04.02", name: "Vigas de concreto f'c=280 kg/cm²", unit: "m3", quantity: 720, unitPrice: 468.5, totalPrice: 337320, isAiGenerated: true, confidence: 0.91 },
        { id: "i_0403", code: "04.03", name: "Losas aligeradas f'c=210 kg/cm²", unit: "m2", quantity: 6400, unitPrice: 148.3, totalPrice: 949120, isAiGenerated: true, confidence: 0.93 },
        { id: "i_0404", code: "04.04", name: "Acero estructural principal", unit: "kg", quantity: 148000, unitPrice: 3.45, totalPrice: 510600, isAiGenerated: true, confidence: 0.9 },
      ],
    },
    {
      id: "sec_05",
      code: "05",
      name: "Muros y Revestimientos",
      subtotal: 980000,
      items: [
        { id: "i_0501", code: "05.01", name: "Muros de ladrillo KK 18 huecos", unit: "m2", quantity: 4800, unitPrice: 82.4, totalPrice: 395520, isAiGenerated: true, confidence: 0.94 },
        { id: "i_0502", code: "05.02", name: "Tarrajeo de muros interiores", unit: "m2", quantity: 9600, unitPrice: 28.6, totalPrice: 274560, isAiGenerated: true, confidence: 0.92 },
        { id: "i_0503", code: "05.03", name: "Cielorraso con mezcla", unit: "m2", quantity: 6400, unitPrice: 48.4, totalPrice: 309760, isAiGenerated: true, confidence: 0.9 },
      ],
    },
    {
      id: "sec_06",
      code: "06",
      name: "Arquitectura y Acabados",
      subtotal: 1840000,
      items: [
        { id: "i_0601", code: "06.01", name: "Fachada vidrio templado sistema spider", unit: "m2", quantity: 2400, unitPrice: 480.0, totalPrice: 1152000, isAiGenerated: true, confidence: 0.83 },
        { id: "i_0602", code: "06.02", name: "Pisos de porcelanato 60x60 primera", unit: "m2", quantity: 5120, unitPrice: 96.5, totalPrice: 494080, isAiGenerated: true, confidence: 0.91 },
        { id: "i_0603", code: "06.03", name: "Puertas contraplacadas", unit: "und", quantity: 160, unitPrice: 850, totalPrice: 136000, isAiGenerated: true, confidence: 0.88 },
        { id: "i_0604", code: "06.04", name: "Pintura látex 2 manos", unit: "m2", quantity: 9600, unitPrice: 6.04, totalPrice: 57984, isAiGenerated: false },
      ],
    },
    {
      id: "sec_07",
      code: "07",
      name: "Instalaciones Especiales",
      subtotal: 636000,
      items: [
        { id: "i_0701", code: "07.01", name: "Ascensores (3 unidades)", unit: "und", quantity: 3, unitPrice: 85000, totalPrice: 255000, isAiGenerated: true, confidence: 0.86 },
        { id: "i_0702", code: "07.02", name: "Sistema HVAC centralizado", unit: "glb", quantity: 1, unitPrice: 180000, totalPrice: 180000, isAiGenerated: true, confidence: 0.82 },
        { id: "i_0703", code: "07.03", name: "Instalaciones eléctricas completas", unit: "glb", quantity: 1, unitPrice: 120000, totalPrice: 120000, isAiGenerated: true, confidence: 0.88 },
        { id: "i_0704", code: "07.04", name: "Sistema contra incendios NFPA", unit: "glb", quantity: 1, unitPrice: 81000, totalPrice: 81000, isAiGenerated: true, confidence: 0.85 },
      ],
    },
  ],
  baseCost: 7236200,
  overheadPct: 0.1,
  profitPct: 0.08,
  contingencyPct: 0.05,
  taxRate: 0.18,
  overheadAmount: 723620,
  profitAmount: 578896,
  contingencyAmount: 361810,
  taxAmount: 1626060,
  totalAmount: 10526586,
  apuSample: {
    itemCode: "04.01",
    itemName: "Columnas de concreto f'c=280 kg/cm²",
    unit: "m3",
    outputQuantity: 10,
    priceDate: "Junio 2026",
    region: "Lima, Perú",
    source: "CAPECO Lima — Boletín Jun-2026",
    materials: [
      { type: "MATERIAL", description: "Cemento Portland Tipo IP", unit: "bls", quantity: 10.0, unitPrice: 15.8, totalPrice: 158.0 },
      { type: "MATERIAL", description: "Arena gruesa", unit: "m3", quantity: 0.54, unitPrice: 88.0, totalPrice: 47.52 },
      { type: "MATERIAL", description: "Grava 3/4\"", unit: "m3", quantity: 0.56, unitPrice: 98.0, totalPrice: 54.88 },
      { type: "MATERIAL", description: "Agua", unit: "m3", quantity: 0.18, unitPrice: 8.0, totalPrice: 1.44 },
      { type: "MATERIAL", description: "Aditivo superplastificante", unit: "lt", quantity: 1.2, unitPrice: 22.0, totalPrice: 26.4 },
      { type: "MATERIAL", description: "Encofrado metálico col.", unit: "m2", quantity: 4.8, unitPrice: 9.4, totalPrice: 45.12 },
    ],
    labor: [
      { type: "LABOR", description: "Capataz", unit: "hh", quantity: 0.08, unitPrice: 28.0, totalPrice: 2.24 },
      { type: "LABOR", description: "Operario", unit: "hh", quantity: 0.64, unitPrice: 22.0, totalPrice: 14.08 },
      { type: "LABOR", description: "Oficial", unit: "hh", quantity: 0.64, unitPrice: 19.0, totalPrice: 12.16 },
      { type: "LABOR", description: "Peón", unit: "hh", quantity: 0.32, unitPrice: 17.0, totalPrice: 5.44 },
      { type: "LABOR", description: "Herramientas (3% MO)", unit: "%MO", quantity: 0.03, unitPrice: 1, totalPrice: 1.02 },
    ],
    equipment: [
      { type: "EQUIPMENT", description: "Vibrador para concreto", unit: "hm", quantity: 0.08, unitPrice: 8.5, totalPrice: 0.68 },
      { type: "EQUIPMENT", description: "Grúa torre", unit: "hm", quantity: 0.2, unitPrice: 180.0, totalPrice: 36.0 },
      { type: "EQUIPMENT", description: "Bomba de concreto", unit: "hm", quantity: 0.1, unitPrice: 85.0, totalPrice: 8.5 },
      { type: "EQUIPMENT", description: "Andamios", unit: "und", quantity: 1.0, unitPrice: 2.8, totalPrice: 2.8 },
    ],
    materialsCost: 333.36,
    laborCost: 34.94,
    equipmentCost: 47.98,
    totalCost: 416.28,
  },
  risks: [
    {
      level: "HIGH",
      title: "Volatilidad del precio del acero corrugado",
      description: "El acero representa el 18.4% del costo directo (S/ 1,331,424). En los últimos 6 meses ha tenido variaciones de ±12%. Una subida del 10% impacta S/ 133,142 adicionales.",
      probability: "Alta",
      impact: "S/ 133,142 (1.3% del total)",
      recommendation: "Incluir cláusula de reajuste de precios en el contrato referenciada al índice de acero del Banco Central.",
    },
    {
      level: "MEDIUM",
      title: "Zona sísmica 4 — diseño estructural especial",
      description: "Edificios de más de 7 pisos en zona sísmica 4 pueden requerir análisis dinámico y aisladores sísmicos en la base según NTE E.030.",
      probability: "Media",
      impact: "S/ 320,000–480,000 (3.1–4.6% del total)",
      recommendation: "Solicitar estudio de mecánica de suelos antes de finalizar el diseño estructural.",
    },
    {
      level: "LOW",
      title: "Plazo de entrega — fachada vidrio spider",
      description: "Los sistemas de vidrio spider tienen 14–18 semanas de fabricación e importación. Con 12 meses de obra, la orden debe realizarse en el mes 2 máximo.",
      probability: "Baja",
      impact: "Ampliación de plazo 4–8 semanas",
      recommendation: "Incluir la compra de fachada como hito crítico en el cronograma del mes 2.",
    },
  ],
}
